export const SYSTEM_ERROR_CODES = {
  JUDGE_SCHEMA_INVALID: "JUDGE_SCHEMA_INVALID",
  JUDGE_LOW_CONFIDENCE: "JUDGE_LOW_CONFIDENCE",
  NARRATE_SCHEMA_INVALID: "NARRATE_SCHEMA_INVALID"
} as const;

export type SystemErrorCode = (typeof SYSTEM_ERROR_CODES)[keyof typeof SYSTEM_ERROR_CODES];
