export const SYSTEM_ERROR_CODES = {
  JUDGE_SCHEMA_INVALID: "JUDGE_SCHEMA_INVALID",
  JUDGE_LOW_CONFIDENCE: "JUDGE_LOW_CONFIDENCE",
  JUDGE_CALL_FAILED: "JUDGE_CALL_FAILED",
  NARRATE_SCHEMA_INVALID: "NARRATE_SCHEMA_INVALID",
  NARRATE_CALL_FAILED: "NARRATE_CALL_FAILED"
} as const;

export type SystemErrorCode = (typeof SYSTEM_ERROR_CODES)[keyof typeof SYSTEM_ERROR_CODES];
